Create sobre
rrafaelc/PI-3-Semestre pull request #22
Opened 2024-06-12 17:28 UTC by RodsAlmeidaR

2024-06-12 17:42 UTC, rrafaelc requested changes
Deixei comentarios

2024-06-12 17:42 UTC, rrafaelc commented on src/app/components/Header.tsx
> +        )}
Não precisa do isLoggedIn, apaga esse trecho do codigo pfv e dai coloca la em cima embaixo da pagina inicial assim

`<Link href="/">Página Inicial</Link>`
`<Link href="/sobre">Sobre</Link>`

2024-06-13 00:33 UTC, rrafaelc approved these changes

2024-06-13 00:35 UTC, Iagooalmeida approved these changes

2024-06-13 00:39 UTC, merged